discussion_7819
WorkQuest/Front-end-DAO pull request #2
Opened 2021-07-09 12:30 UTC by FlambergTomsk

2021-07-12 11:51 UTC, alexdan93 requested changes
БЭМ нужно сильно поправить, не пушить .nuxt файлы. Визуальные правки скинул скринами в личку

2021-07-12 11:51 UTC, alexdan93 commented on assets/img/ui/arrowRight.svg
> +<svg width="16" height="12" viewBox="0 0 16 12" fill="none" xmlns="http://www.w3.org/2000/svg">
на проекте подключен иконочный шрифт, используй его

2021-07-12 11:51 UTC, alexdan93 commented on components/ui/DiscussionCard/index.vue
> +        src="~assets/img/ui/star_simple.svg"
используй иконочный шрифт

2021-07-12 11:51 UTC, alexdan93 commented on components/ui/DiscussionCard/index.vue
> +        Description
вынеси в файл локализации

2021-07-12 11:51 UTC, alexdan93 commented on components/ui/DiscussionCard/index.vue
> +    <div class="discussion__description-title">
лучше использовать класс subtitle и по возможности избегать двойного имени у элементов

2021-07-12 11:51 UTC, alexdan93 commented on components/ui/DiscussionCard/index.vue
> +        <div class="discussion__bottom-link-text">
в таких случаях лучше пользоваться служебными блоками. Т.е. классы будут выглядеть так disscussion__botom => disscussion__link link => link__text

2021-07-12 11:51 UTC, alexdan93 commented on components/ui/DiscussionCard/index.vue
> +          50
заведи переменную под числа в data

2021-07-12 11:51 UTC, alexdan93 commented on components/ui/DiscussionCard/index.vue
> +      font-style: normal;
нормал стили не нужно копировать, если эти свойства не изменены у родителя

2021-07-12 11:51 UTC, alexdan93 commented on components/ui/DiscussionCard/index.vue
> +    &-name {
у элемента в наследовании может быть только модификатор. Так же любое наследование идет через нижнее подчеркивание, дефис в наследовании не допускается. Т.е. &-name нельзя, а &__user-name можно. Как правило можно обойтись просто &__name

2021-07-12 11:51 UTC, alexdan93 commented on components/ui/DiscussionCard/index.vue
> +    margin: 25.5px 0px 10px 0px;
старайся не использовать десятичные дроби в пикселях, если нет крайней необходимости

2021-07-13 01:21 UTC, FlambergTomsk commented on components/ui/DiscussionCard/index.vue
> +          50
Done

2021-07-13 01:24 UTC, FlambergTomsk commented on components/ui/DiscussionCard/index.vue
> +      font-style: normal;
Done

2021-07-13 01:42 UTC, FlambergTomsk commented on components/ui/DiscussionCard/index.vue
> +    margin: 25.5px 0px 10px 0px;
Исправлен отступ от заголовка discussion-title до 25px.
Отступы от nuxt-link округлены в большую сторону до 7px.
line-height comment-counter & like-counter округлены до 18px.

2021-07-13 02:11 UTC, FlambergTomsk commented on components/ui/DiscussionCard/index.vue
> +    &-name {
Done

2021-07-13 08:28 UTC, alexdan93 commented on components/ui/DiscussionCard/index.vue
> +      <button>
Класс нужно задавать основному тэгу. У тэга span в этом случае можно оставить только класс иконочного шрифта.

2021-07-13 08:28 UTC, alexdan93 commented on components/ui/DiscussionCard/index.vue
> +      <div class="discussion__bottom-numbers">
bottom-numbers и bottom-counter имеют одинаковое назначение. задай один класс и первому, если нужен отступ задай модификатор

2021-07-13 08:28 UTC, alexdan93 commented on components/ui/DiscussionCard/index.vue
>      <div class="discussion__bottom">
сделай вложенный блок footer, это поможет тебе не писать двойные имена классов.

2021-07-13 08:28 UTC, alexdan93 commented on components/ui/DiscussionCard/index.vue
> +        <img
так и не заменил картинку иконочным шрифтом

2021-07-13 08:28 UTC, alexdan93 commented on components/ui/DiscussionCard/index.vue
>        <h4>
не пользуйся тегами h1-h5 без необходимости, стилизуй размером и жирностью

2021-07-13 08:28 UTC, alexdan93 commented on components/ui/DiscussionCard/index.vue
> +.icon-short_right:before {
не используй классы иконочного шрифта для стилизации. Используй класс элемента

2021-07-13 08:28 UTC, alexdan93 commented on pages/discussions/index.vue
> +    &__header-search {
не вижу других поисков на странице, почему header-search а не просто search?

2021-07-13 08:28 UTC, alexdan93 commented on pages/discussions/index.vue
> +    &__header-btn {
аналогично

2021-07-13 08:49 UTC, FlambergTomsk commented on pages/discussions/index.vue
> +    &__header-btn {
Done

2021-07-13 08:49 UTC, FlambergTomsk commented on pages/discussions/index.vue
> +    &__header-search {
Done

2021-07-13 09:10 UTC, FlambergTomsk commented on components/ui/DiscussionCard/index.vue
> +      <button>
Done

2021-07-13 09:30 UTC, FlambergTomsk commented on components/ui/DiscussionCard/index.vue
> +      <div class="discussion__bottom-numbers">
Done

2021-07-13 09:41 UTC, FlambergTomsk commented on components/ui/DiscussionCard/index.vue
> +        <img
Done

2021-07-13 09:45 UTC, FlambergTomsk commented on components/ui/DiscussionCard/index.vue
>        <h4>
Done

2021-07-13 12:51 UTC, FlambergTomsk commented on components/ui/DiscussionCard/index.vue
>      <div class="discussion__bottom">
Done

2021-07-27 04:20 UTC, alexdan93 commented on pages/proposals/index.vue
> +s<template>
?

2021-07-27 04:30 UTC, merged